// campos de la tabla editable
export const ESTRUCTURA_DATOS_POR_CLAVE: Record<string, Array<{
  campo: string;
  tipo: string;
  obligatorio?: boolean;
  Descripcion?: string
}>> = {
  // Marco Jurídico (MJ01)
  MJ01: [
    { campo: "Ordenamiento", tipo: "string", obligatorio: true, Descripcion: "Ordenamiento Jurídico Aplicable" },
    { campo: "Titulo", tipo: "string", obligatorio: true, Descripcion: "Título del Asunto Relevante" },
    { campo: "Fecha de emision", tipo: "date", obligatorio: true, Descripcion: "Fecha de emisión del documento que sustenta el asunto relevante" },
  ]
  ,
  // Planeacion (PP01)
  PP02: [
    { campo: "Tipo de Documento", tipo: "string", obligatorio: true, Descripcion: "Nombre del programa" },
    { campo: "Nombre ", tipo: "string", obligatorio: true, Descripcion: "Descripción del programa" },
    { campo: "Fecha", tipo: "date", obligatorio: true, Descripcion: "Fecha de emisión del programa" },
    { campo: "Observaciones", tipo: "string", obligatorio: false, Descripcion: "Observaciones adicionales sobre el programa" },
  ],

  //Derechos y Obligaciones (DO01-DO04)
  DO01: [
    { campo: "Nombre y puesto del servidor que otorga el poder", tipo: "string", obligatorio: true, Descripcion: "Nombre y puesto del servidor que otorga el poder" },
    { campo: "Tipo de poder otorgado", tipo: "string", obligatorio: true, Descripcion: "Tipo de poder otorgado" },
    { campo: "Especificar", tipo: "string", obligatorio: true, Descripcion: "Fecha de otorgamiento del poder" },
    { campo: "Fecha de Expedición", tipo: "date", obligatorio: true, Descripcion: "Fecha de expedición del poder" },
    { campo: "Notario Público que autoriza el poder", tipo: "string", obligatorio: true, Descripcion: "Notario Público que autoriza el poder" },
    { campo: "Inscrito en el Registro Público de la Propiedad y del Comercio", tipo: "string", obligatorio: true, Descripcion: "Número de inscripción en el Registro Público de la Propiedad y del Comercio" },
    { campo: "Observaciones", tipo: "string", obligatorio: false, Descripcion: "Observaciones adicionales sobre el poder otorgado" },
  ],

  DO02: [
    { campo: "Datos de la sesion: Numero de sesion", tipo: "string", obligatorio: true, Descripcion: "Número de sesión" },
    { campo: "Datos de la sesion: Fecha de sesion", tipo: "string", obligatorio: true, Descripcion: "Fecha de la sesión" },
    { campo: "Datos de la sesion: Ordinaria o Extraordinaria", tipo: "string", obligatorio: true, Descripcion: "Tipo de sesión (Ordinaria o Extraordinaria)" },
    { campo: "Datos del acuerdo: Numero", tipo: "string", obligatorio: true, Descripcion: "Número del acuerdo" },
    { campo: "Datos del acuerdo: Descripcion Breve", tipo: "string", obligatorio: true, Descripcion: "Descripción detallada de los acuerdos tomados en la sesión" },
    { campo: "Datos del acuerdo: Responsable", tipo: "string", obligatorio: true, Descripcion: "Nombre del responsable de dar seguimiento a los acuerdos" },
    { campo: "Datos del acuerdo: Áreas involucradas", tipo: "string", obligatorio: true, Descripcion: "Áreas involucradas en el seguimiento de los acuerdos" },
    { campo: "Datos del acuerdo: Porcentaje de avance", tipo: "number", obligatorio: true, Descripcion: "Porcentaje de avance en el seguimiento de los acuerdos" },
    { campo: "Datos del acuerdo: Comentarios", tipo: "string", obligatorio: false, Descripcion: "Comentarios adicionales sobre el seguimiento de los acuerdos" },
  ],
  DO03: [
    { campo: "Auditoria realizada por", tipo: "string", obligatorio: true, Descripcion: "Nombre del ente auditor que realizó la auditoría" },
    { campo: "Periodo auditado: desde", tipo: "string", obligatorio: true, Descripcion: "Fecha de inicio del periodo auditado" },
    { campo: "Periodo auditado: hasta", tipo: "string", obligatorio: true, Descripcion: "Fecha de fin del periodo auditado" },
    { campo: "Tipo de auditoría", tipo: "string", obligatorio: true, Descripcion: "Tipo de auditoría realizada (financiera, de cumplimiento, etc.)" },
    { campo: "Observaciones", tipo: "string", obligatorio: false, Descripcion: "Observaciones adicionales sobre la auditoría realizada" },
    { campo: "Observaciones atendidas", tipo: "string", obligatorio: false, Descripcion: "Observaciones de auditoría que han sido atendidas" },
    { campo: "Observaciones pendientes", tipo: "string", obligatorio: false, Descripcion: "Observaciones de auditoría que aún están pendientes de atender" },
    { campo: "Situación actual", tipo: "string", obligatorio: false, Descripcion: "Situación actual de las observaciones de auditoría (atendidas, pendientes, etc.)" },
  ],
  DO04: [
    { campo: "Cargo", tipo: "string", obligatorio: true, Descripcion: "Cargo del responsable" },
    { campo: "Con derecho a ", tipo: "string", obligatorio: true, Descripcion: "Derechos asociados al cargo" },
    { campo: "Fecha de inicio del cargo", tipo: "string", obligatorio: true, Descripcion: "Fecha de inicio del cargo" },
    { campo: "Periodicidad con que se reúnen", tipo: "string", obligatorio: true, Descripcion: "Periodicidad con que se reúnen los responsables" },
    { campo: "Observaciones", tipo: "string", obligatorio: false, Descripcion: "Observaciones adicionales sobre las representaciones y cargos honoríficos" },
  ],

  // EO - Organizacion
  EO02: [
    { campo: "Tipo", tipo: "string", obligatorio: true, Descripcion: "Tipo de reglamento o manual" },
    { campo: "Fecha de Actualización, Autorización ó Publicación", tipo: "date", obligatorio: true, Descripcion: "Fecha de actualización, autorización o publicación del reglamento o manual" },
    { campo: "Observaciones", tipo: "string", obligatorio: false, Descripcion: "Observaciones adicionales sobre el reglamento o manual" },
  ],

  // RH - Recursos Humanos
  RH01: [
    { campo: "Número de empleado", tipo: "string", obligatorio: true, Descripcion: "Número de empleado del personal de base" },
    { campo: "Nombre", tipo: "string", obligatorio: true, Descripcion: "Nombre completo del personal de base" },
    { campo: "RFC", tipo: "string", obligatorio: true, Descripcion: "RFC del personal de base" },
    { campo: "Plaza (Categoría)", tipo: "string", obligatorio: true, Descripcion: "Plaza o categoría del personal de base" },
    { campo: "Tipo", tipo: "string", obligatorio: true, Descripcion: "Tipo de personal (base, apoyo, comisionado, honorarios)" },
    { campo: "Fecha de ingreso", tipo: "string", obligatorio: true, Descripcion: "Fecha de ingreso del personal a la dependencia" },
    { campo: "Sueldo", tipo: "number", obligatorio: true, Descripcion: "Sueldo del personal de base" },
    { campo: "Otras percepciones", tipo: "number", obligatorio: false, Descripcion: "Otras percepciones económicas del personal de base" },
    { campo: "Total", tipo: "number", obligatorio: true, Descripcion: "Total de percepciones económicas del personal de base" },
    { campo: "Unidad de Adscripción (UPP)", tipo: "string", obligatorio: true, Descripcion: "Unidad de adscripción del personal de base" },
    { campo: "Área Laboral (UR)", tipo: "string", obligatorio: true, Descripcion: "Área laboral del personal de base" },
    { campo: "Observaciones", tipo: "string", obligatorio: false, Descripcion: "Observaciones adicionales sobre el personal de base" },
  ],
  RH02: [
    { campo: "Número de empleado", tipo: "string", obligatorio: true, Descripcion: "Número de empleado del personal de apoyo" },
    { campo: "Nombre", tipo: "string", obligatorio: true, Descripcion: "Nombre completo del personal de apoyo" },
    { campo: "RFC", tipo: "string", obligatorio: true, Descripcion: "RFC del personal de apoyo" },
    { campo: "Plaza (Categoría)", tipo: "string", obligatorio: true, Descripcion: "Plaza o categoría del personal de apoyo" },
    { campo: "Tipo", tipo: "string", obligatorio: true, Descripcion: "Tipo de personal (base, apoyo, comisionado, honorarios)" },
    { campo: "Fecha de ingreso", tipo: "string", obligatorio: true, Descripcion: "Fecha de ingreso del personal a la dependencia" },
    { campo: "Sueldo", tipo: "number", obligatorio: true, Descripcion: "Sueldo del personal de apoyo" },
    { campo: "Otras percepciones", tipo: "number", obligatorio: false, Descripcion: "Otras percepciones económicas del personal de apoyo" },
    { campo: "Total", tipo: "number", obligatorio: true, Descripcion: "Total de percepciones económicas del personal de apoyo" },
    { campo: "Unidad de Adscripción (UPP)", tipo: "string", obligatorio: true, Descripcion: "Unidad de adscripción del personal de apoyo" },
    { campo: "Área Laboral (UR)", tipo: "string", obligatorio: true, Descripcion: "Área laboral del personal de apoyo" },
    { campo: "Observaciones", tipo: "string", obligatorio: false, Descripcion: "Observaciones adicionales sobre el personal de apoyo" },
  ],
  RH03: [
    { campo: "Número de empleado", tipo: "string", obligatorio: true, Descripcion: "Número de empleado del personal comisionado" },
    { campo: "Nombre", tipo: "string", obligatorio: true, Descripcion: "Nombre completo del personal comisionado" },
    { campo: "RFC", tipo: "string", obligatorio: true, Descripcion: "RFC del personal comisionado" },
    { campo: "Categoría: Denominación", tipo: "string", obligatorio: true, Descripcion: "Plaza o categoría del personal comisionado" },
    { campo: "Tipo", tipo: "string", obligatorio: true, Descripcion: "Tipo de personal (base, apoyo, comisionado, honorarios)" },
    { campo: "Unidad de Adscripción (UPP)", tipo: "string", obligatorio: true, Descripcion: "Unidad de adscripción del personal comisionado" },
    { campo: "Comisionado a: UR", tipo: "string", obligatorio: true, Descripcion: "Dependencia o entidad a la que el personal comisionado está asignado" },
    { campo: "Referencia Documental (Oficio)", tipo: "string", obligatorio: true, Descripcion: "Referencia documental que sustenta la comisión del personal" },
    { campo: "Inicio de comisión", tipo: "string", obligatorio: true, Descripcion: "Fecha de inicio de la comisión del personal" },
    { campo: "Fin de comisión", tipo: "string", obligatorio: true, Descripcion: "Fecha de fin de la comisión del personal" },
    { campo: "Sueldo", tipo: "number", obligatorio: true, Descripcion: "Sueldo del personal comisionado" },
    { campo: "Otras percepciones", tipo: "number", obligatorio: false, Descripcion: "Otras percepciones económicas del personal comisionado" },
    { campo: "Observaciones", tipo: "string", obligatorio: false, Descripcion: "Observaciones adicionales sobre el personal comisionado" },
  ]
  ,
  RH04: [
    { campo: "Nombre", tipo: "string", obligatorio: true, Descripcion: "Nombre completo del personal de honorarios" },
    { campo: "RFC", tipo: "string", obligatorio: true, Descripcion: "RFC del personal de honorarios" },
    { campo: "Fecha de Inicio de contrato", tipo: "string", obligatorio: true, Descripcion: "Fecha de inicio del contrato del personal de honorarios" },
    { campo: "Fecha de fin de contrato", tipo: "string", obligatorio: true, Descripcion: "Fecha de fin del contrato del personal de honorarios" },
    { campo: "Fuente de Recurso", tipo: "string", obligatorio: true, Descripcion: "Fuente de recursos para el pago del personal de honorarios" },
    { campo: "Actividades a Desarrollar", tipo: "string", obligatorio: true, Descripcion: "Descripción de las actividades a desarrollar por el personal de honorarios" },
    { campo: "Salario", tipo: "number", obligatorio: true, Descripcion: "Salario del personal de honorarios" },
    { campo: "Otras percepciones", tipo: "number", obligatorio: false, Descripcion: "Otras percepciones económicas del personal de honorarios" },
    { campo: "Total", tipo: "number", obligatorio: true, Descripcion: "Total de percepciones económicas del personal de honorarios" },
    { campo: "Unidad de Adscripción (UPP)", tipo: "string", obligatorio: true, Descripcion: "Unidad de adscripción del personal de honorarios" },
    { campo: "Área Laboral (UR)", tipo: "string", obligatorio: true, Descripcion: "Área laboral del personal de honorarios" },
    { campo: "Observaciones", tipo: "string", obligatorio: false, Descripcion: "Observaciones adicionales sobre el personal de honorarios" },
  ]

  // recursos financieros (RF01-RF14)

  ,
  RF01: [
    { campo: "Partida", tipo: "string", obligatorio: true, Descripcion: "Partida" },
    { campo: "Denominacion", tipo: "string", obligatorio: true, Descripcion: "Denominación" },
    { campo: "Presupuesto: Autorizado", tipo: "number", obligatorio: true },
    { campo: "Presupuesto: Ampliaciones y/o reducciones", tipo: "number", obligatorio: true },
    { campo: "Presupuesto: Modificado", tipo: "number", obligatorio: true },
    { campo: "Presupuesto: Ejercido", tipo: "number", obligatorio: true },
    { campo: "Presupuesto: Por ejercer", tipo: "number", obligatorio: true },
    { campo: "Observaciones", tipo: "string", obligatorio: false, Descripcion: "Observaciones adicionales sobre el presupuesto por partida" },
  ],

  RF02: [
    { campo: "Origen del Recurso: Partida", tipo: "string", obligatorio: true, Descripcion: "Partida" },
    { campo: "Origen del Recurso: Descripción", tipo: "string", obligatorio: true, Descripcion: "Descripción" },
    { campo: "Presupuesto:Importe Autorizado", tipo: "number" },
    { campo: "Presupuesto:Importe Ampliaciones y/o reducciones", tipo: "number" },
    { campo: "Presupuesto:Importe Modificado", tipo: "number" },
    { campo: "Presupuesto:Importe Ejercido", tipo: "number" },
    { campo: "Presupuesto:Importe Por ejercer", tipo: "number" },
    { campo: "Observaciones ", tipo: "string", obligatorio: false, Descripcion: "Observaciones adicionales sobre el presupuesto por origen de recurso" },

  ],

  RF03: [
    { campo: "Ramo", tipo: "string", obligatorio: true },
    { campo: "Programa", tipo: "string", obligatorio: true },
    { campo: "Dependencia Ejecutora", tipo: "string", obligatorio: true },
    { campo: "Número del Convenio o Referencia de la Autorización", tipo: "string", obligatorio: true },
    { campo: "Importe: Aprobado", tipo: "object", obligatorio: true },
    { campo: "Importe: Modificado", tipo: "number" },
    { campo: "Importe: Ejercido", tipo: "number" },
    { campo: "Importe: Por ejercer", tipo: "number" },
    { campo: "Número de Acciones: Aprobadas", tipo: "number" },
    { campo: "Número de Acciones: Ejecutadas", tipo: "number" },
    { campo: "Número de Acciones: Pendientes", tipo: "number" },
    { campo: "Observaciones", tipo: "string", obligatorio: false },
  ],

  RF04: [
    { campo: "Nombre del Programa", tipo: "string", obligatorio: true },
    { campo: "Numero del Capitulo", tipo: "number", obligatorio: true },
    { campo: "Nombre del Capitulo", tipo: "string", obligatorio: true },
    { campo: "Presupuesto: Autorizado", tipo: "number" },
    { campo: "Presupuesto: Ampliaciones y/o reducciones", tipo: "number" },
    { campo: "Presupuesto: Modificado", tipo: "number" },
    { campo: "Presupuesto: Ejercido", tipo: "number" },
    { campo: "Presupuesto: Por ejercer", tipo: "number" },
    { campo: "Observaciones", tipo: "string", obligatorio: false, Descripcion: "Observaciones adicionales sobre el presupuesto por programa" }
  ],

  RF05: [
    { campo: "Numero de Cuenta", tipo: "string", obligatorio: true },
    { campo: "Firmas Registradas: Nombre", tipo: "array", obligatorio: true },
    { campo: "Firmas Registradas: Cargo", tipo: "array", obligatorio: true },
    { campo: "Folio Ultimo Cheque", tipo: "number", obligatorio: true },
    { campo: "Saldo Segun Banco", tipo: "number", obligatorio: true },
    { campo: "Cargos No Correspondidos", tipo: "number", obligatorio: true },
    { campo: "Abonos No Correspondidos", tipo: "number", obligatorio: true },
    { campo: "Saldo Segun Registros", tipo: "number", obligatorio: true },
    { campo: "Responsable del Manejo", tipo: "string", obligatorio: true },
  ],

  RF06: [
    { campo: "Numero de Oficio Autorizacion", tipo: "string", obligatorio: true },
    { campo: "Fecha de Oficio", tipo: "date", obligatorio: true },
    { campo: "Nombre del Responsable", tipo: "string", obligatorio: true },
    { campo: "Cargo del Responsable", tipo: "string", obligatorio: true },
    { campo: "Importe a Verificar", tipo: "number", obligatorio: true },
    { campo: "Destino del Fondo", tipo: "string", obligatorio: true },
    { campo: "Resultados del ultimo Arqueo Practicado", tipo: "string", obligatorio: true },
    { campo: "Saldo en Cuenta de Cheques: No. de cuenta", tipo: "array", obligatorio: true },
    { campo: "Saldo en Cuenta de Cheques: Banco", tipo: "array", obligatorio: true },
    { campo: "Saldo en Cuenta de Cheques: Fecha", tipo: "array", obligatorio: true },
    { campo: "Saldo en Cuenta de Cheques: Saldo", tipo: "array", obligatorio: false },
    { campo: "Monto Disponible en Efectivo", tipo: "number", obligatorio: true },
    { campo: "Comprobantes: Acreedores diversos", tipo: "array", obligatorio: true },
    { campo: "Comprobantes: Deudores Diversos", tipo: "array", obligatorio: true },
    { campo: "Comprobantes: Documentos por Recuperar", tipo: "array", obligatorio: true },
  ],

  RF07: [
    { campo: "Numero de Folio de Contrarrecibo", tipo: "number", obligatorio: true, Descripcion: "Número de Folio del Contrarrecibo" },
    { campo: "Nombre del Beneficiario", tipo: "string", obligatorio: true, Descripcion: "Nombre del Beneficiario" },
    { campo: "Fecha de recepcion", tipo: "date", obligatorio: true, Descripcion: "Fecha de Recepción" },
    { campo: "Número de estimacion o factura", tipo: "date", obligatorio: true, Descripcion: "Fecha de Recepción" },
    { campo: "Importe Total", tipo: "number", obligatorio: true, Descripcion: "Importe Total" },
    { campo: "Observaciones", tipo: "string", obligatorio: false, Descripcion: "Observaciones" },
  ],

  RF08: [
    { campo: "Fecha", tipo: "date", obligatorio: true, Descripcion: "Fecha" },
    { campo: "Número de Cheque", tipo: "number", obligatorio: true, Descripcion: "Número de Cheque" },
    { campo: "Cuenta", tipo: "number", obligatorio: true, Descripcion: "Cuenta" },
    { campo: "Banco", tipo: "string", obligatorio: true, Descripcion: "Banco" },
    { campo: "Monto", tipo: "number", obligatorio: true, Descripcion: "Monto" },
    { campo: "Nombre del Beneficiario", tipo: "string", obligatorio: true, Descripcion: "Nombre del Beneficiario" },
    { campo: "Concepto", tipo: "string", obligatorio: true, Descripcion: "Concepto" },
    { campo: "Observaciones", tipo: "string", obligatorio: false, Descripcion: "Observaciones" },
  ],

  RF09: [
    { campo: "Area Generadora del Ingreso", tipo: "string", obligatorio: true, Descripcion: "Área Generadora del Ingreso" },
    { campo: "Concepto que da Origen al Ingreso", tipo: "string", obligatorio: true, Descripcion: "Concepto del Ingreso" },
    { campo: "Fecha Ingreso", tipo: "date", obligatorio: true, Descripcion: "Fecha del Ingreso" },
    { campo: "Documento que identifica al Ingreso", tipo: "string", obligatorio: true, Descripcion: "Documento del Ingreso" },
    { campo: "Importe del ingreso: Monto", tipo: "number", obligatorio: true, Descripcion: "Importe del Ingreso" },
    { campo: "Importe del ingreso: Cuenta Bancaria Donde se Depositara", tipo: "string", obligatorio: true, Descripcion: "Cuenta Bancaria" },
    { campo: "Importe del ingreso: Institucion Bancaria", tipo: "string", obligatorio: true, Descripcion: "Institución Bancaria" },
    { campo: "Responsable de la Custodia: Nombre y cargo", tipo: "string", obligatorio: true, Descripcion: "Responsable de la Custodia" },
    { campo: "Observaciones", tipo: "string", obligatorio: false, Descripcion: "Observaciones" },
  ],

  RF11: [
    { campo: "Nombre del Deudor", tipo: "string", obligatorio: true, Descripcion: "Nombre del Deudor" },
    { campo: "Concepto", tipo: "string", obligatorio: true, Descripcion: "Concepto" },
    { campo: "Documento que acredita la cuenta por cobrar: Fecha", tipo: "date", obligatorio: true, Descripcion: "Fecha del Documento" },
    { campo: "Documento que acredita la cuenta por cobrar: Tipo", tipo: "string", obligatorio: true, Descripcion: "Tipo de Documento" },
    { campo: "Documento que acredita la cuenta por cobrar: Folio", tipo: "string", obligatorio: true, Descripcion: "Folio" },
    { campo: "Documento que acredita la cuenta por cobrar: Importe", tipo: "number", obligatorio: true, Descripcion: "Importe" },
    { campo: "Documento que acredita la cuenta por cobrar: Fecha Vencimiento", tipo: "date", obligatorio: true, Descripcion: "Fecha de Vencimiento" },
    { campo: "Documento que acredita la cuenta por cobrar: Número Contable", tipo: "number", obligatorio: true, Descripcion: "Número Contable" },
    { campo: "Documento que acredita la cuenta por cobrar: Titulo", tipo: "string", obligatorio: true, Descripcion: "Título" },
    { campo: "Documento que acredita la cuenta por cobrar: Saldo Vencido", tipo: "number", obligatorio: true, Descripcion: "Saldo Vencido" },
    { campo: "Observaciones", tipo: "string", obligatorio: false, Descripcion: "Observaciones" },
  ],

  RF12: [
    { campo: "Concepto", tipo: "string", obligatorio: true, Descripcion: "Concepto" },
    { campo: "Documento que acredita la cuenta por pagar: Fecha", tipo: "date", obligatorio: true, Descripcion: "Fecha del Documento" },
    { campo: "Documento que acredita la cuenta por pagar: Tipo", tipo: "string", obligatorio: true, Descripcion: "Tipo de Documento" },
    { campo: "Documento que acredita la cuenta por pagar: Folio", tipo: "string", obligatorio: true, Descripcion: "Folio" },
    { campo: "Documento que acredita la cuenta por pagar: Dependencia", tipo: "string", obligatorio: true, Descripcion: "Dependencia" },
    { campo: "Documento que acredita la cuenta por pagar: Partida", tipo: "string", obligatorio: true, Descripcion: "Partida" },
    { campo: "Documento que acredita la cuenta por pagar: Fecha de Vencimiento", tipo: "date", obligatorio: true, Descripcion: "Fecha de Vencimiento" },
    { campo: "Datos de la cuenta por pagar: Numero", tipo: "number", obligatorio: true, Descripcion: "Número" },
    { campo: "Datos de la cuenta por pagar: Titulo", tipo: "string", obligatorio: true, Descripcion: "Título" },
    { campo: "Datos de la cuenta por pagar: Saldo Vencido", tipo: "number", obligatorio: true, Descripcion: "Saldo Vencido" },
    { campo: "Observaciones", tipo: "string", obligatorio: false, Descripcion: "Observaciones" },
  ],

  RF13: [
    { campo: "Concepto del mpuesto", tipo: "string", obligatorio: true, Descripcion: "Concepto del Impuesto" },
    { campo: "Enteros provisionales: Periodo Por Pagar", tipo: "string", obligatorio: true, Descripcion: "Periodo por pagar (Enteros Provisionales)" },
    { campo: "Enteros provisionales: Periodo T/D", tipo: "string", obligatorio: true, Descripcion: "Periodo T/D (Enteros Provisionales)" },
    { campo: "Enteros provisionales: Importe Por Pagar", tipo: "number", obligatorio: true, Descripcion: "Importe por pagar (Enteros Provisionales)" },
    { campo: "Enteros provisionales: Importe Clave", tipo: "string", obligatorio: true, Descripcion: "Clave del importe (Enteros Provisionales)" },
    { campo: "Enteros provisionales: Multas y Recargos", tipo: "number", obligatorio: true, Descripcion: "Multas y Recargos" },
    { campo: "Declaraciones anuales: Presentadas", tipo: "number", obligatorio: true, Descripcion: "Declaraciones Anuales Presentadas" },
    { campo: "Declaraciones anuales: Por Presentar", tipo: "number", obligatorio: true, Descripcion: "Declaraciones Anuales por Presentar" },
    { campo: "Declaraciones anuales: Año", tipo: "number", obligatorio: true, Descripcion: "Año de Declaraciones" },
    { campo: "Declaraciones anuales: Importe", tipo: "number", obligatorio: true, Descripcion: "Importe de Declaraciones Anuales" },
    { campo: "Observaciones", tipo: "string", obligatorio: false, Descripcion: "Observaciones" },
  ],

  RF14: [
    { campo: "Tipo de Póliza", tipo: "string", obligatorio: true, Descripcion: "Tipo de Póliza" },
    { campo: "Compañía", tipo: "string", obligatorio: true, Descripcion: "Compañía" },
    { campo: "Monto", tipo: "number", obligatorio: true, Descripcion: "Monto" },
    { campo: "Cobertura", tipo: "string", obligatorio: true, Descripcion: "Cobertura" },
    { campo: "Vigencia: desde", tipo: "date", obligatorio: true, Descripcion: "Vigencia" },
    { campo: "Vigencia: hasta", tipo: "date", obligatorio: true, Descripcion: "Vigencia" },
    { campo: "Observaciones", tipo: "string", obligatorio: false, Descripcion: "Observaciones" },
  ],

  RF15: [
    { campo: "Número de Póliza", tipo: "string", obligatorio: true, Descripcion: "Número de Póliza" },
    { campo: "Compañía Aseguradora", tipo: "string", obligatorio: true, Descripcion: "Compañía Aseguradora" },
    { campo: "Tipo de Fianza o garantía", tipo: "string", obligatorio: true, Descripcion: "Tipo de Fianza o Garantía" },
    { campo: "Concepto u obra de la fianza o garantía", tipo: "string", obligatorio: true, Descripcion: "Concepto u Obra de la Fianza o Garantía" },
    { campo: "Cobertura de la fianza o garantía", tipo: "string", obligatorio: true, Descripcion: "Cobertura de la Fianza o Garantía" },
    { campo: "Vigencia: desde", tipo: "date", obligatorio: true, Descripcion: "Vigencia" },
    { campo: "Vigencia: hasta", tipo: "date", obligatorio: true, Descripcion: "Vigencia" },
    { campo: "Observaciones", tipo: "string", obligatorio: false, Descripcion: "Observaciones" },
  ],

  RF16: [
    { campo: "Descripcio del Convenio o Contrato", tipo: "string", obligatorio: true, Descripcion: "Descripción del Convenio o Contrato" },
    { campo: "Nombre de Quien conviene o Contrata por la Unidad Responsable", tipo: "string", obligatorio: true, Descripcion: "Nombre de quien conviene o contrata" },
    { campo: "Importe", tipo: "number", obligatorio: true, Descripcion: "Importe" },
    { campo: "Periodo", tipo: "string", obligatorio: true, Descripcion: "Periodo" },
  ],

  RF17: [
    { campo: "Tipo de Documento", tipo: "string", obligatorio: true, Descripcion: "Tipo de Documento" },
    { campo: "Folio: desde", tipo: "string", obligatorio: true, Descripcion: "Folio" },
    { campo: "Folio: hasta", tipo: "string", obligatorio: true, Descripcion: "Folio" },
    { campo: "Fecha de Último Registro", tipo: "date", obligatorio: true, Descripcion: "Fecha de Último Registro" },
    { campo: "Observaciones", tipo: "string", obligatorio: false, Descripcion: "Observaciones" },
  ],

  // anexos de contratos y obras (OP01-OP04)

  OP01: [
    { campo: "No. de Expediente", tipo: "string", obligatorio: true, Descripcion: "No. de Expediente" },
    { campo: "Clave de Contrato", tipo: "string", obligatorio: true, Descripcion: "Clave de contrato o Acuerdo" },
    { campo: "Nombre de Obra y Ubicación", tipo: "string", obligatorio: true, Descripcion: "Nombre de Obra y Ubicación" },
    { campo: "Fecha de Contrato", tipo: "date", obligatorio: true, Descripcion: "Fecha de contrato o acuerdo" },
    { campo: "Estado de Obra", tipo: "string", obligatorio: true, Descripcion: "Estado de la Obra" },
    { campo: "Fuente de Financiamiento", tipo: "string", obligatorio: true, Descripcion: "Fuente de Financiamiento" },
    { campo: "Origen de Recurso", tipo: "string", obligatorio: true, Descripcion: "Origen de Recurso" },
    { campo: "Suficiencia Presupuestal", tipo: "string", obligatorio: true, Descripcion: "Suficiencia Presupuestal" },
    { campo: "Monto Contratado", tipo: "number", obligatorio: true, Descripcion: "Monto Contratado" },
    { campo: "Monto Ejercido", tipo: "number", obligatorio: true, Descripcion: "Monto ejercido" },
    { campo: "Avance Físico (%)", tipo: "number", obligatorio: true, Descripcion: "Avance Físico (%)" },
    { campo: "Avance Financiero (%)", tipo: "number", obligatorio: true, Descripcion: "Avance Financiero (%)" },
    { campo: "Modalidad de Contratación", tipo: "string", obligatorio: true, Descripcion: "Modalidad de Contratación" },
  ],

  OP02: [
    { campo: "No. de Expediente", tipo: "string", obligatorio: true, Descripcion: "No. de Expediente" },
    { campo: "Tipo de Obra", tipo: "string", obligatorio: true, Descripcion: "Tipo de Obra" },
    { campo: "Programa de Inversión", tipo: "string", obligatorio: true, Descripcion: "Programa de Inversión" },
    { campo: "Nombre de la Obra", tipo: "string", obligatorio: true, Descripcion: "Nombre de la Obra" },
    { campo: "Municipio", tipo: "string", obligatorio: true, Descripcion: "Municipio" },
    { campo: "Localidad", tipo: "string", obligatorio: true, Descripcion: "Localidad" },
    { campo: "Dependencia Beneficiada", tipo: "string", obligatorio: true, Descripcion: "Dependencia Beneficiada" },
    { campo: "Ejercicio Presupuestal", tipo: "number", obligatorio: true, Descripcion: "Ejercicio Presupuestal" },
    { campo: "Ejecutora", tipo: "string", obligatorio: true, Descripcion: "Ejecutora" },
    { campo: "Expediente Tecnico: Solicitud de Obra", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Expediente Tecnico: Cedula Basica de la Obra", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Aprovacione de Montos, Limitesy rangos para el ejercicio de las Obras", tipo: "string", obligatorio: true, Descripcion: "Aprobaciones de montos, límites y rangos para el ejercicio de las obras" },
    { campo: "Expediente tecnico: Acuerdo de Ejecucion (Acta de Comité de Obras y Servicios)", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Expediente tecnico: Programa Anual de Obras y Servicios", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Expediente tecnico: Estudios de factibilidad", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Estudios de Impacto Ambiental", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Expediente tecnico: Metas y descripcion del proyecto", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Expediente tecnico: Procedimiento Constructivo", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Expediente tecnico: Planos", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Expediente tecnico: Resumen del Presupuesto", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Expediente tecnico: Programa de Ejecucion", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Expediente tecnico: Croquis de Macro y Micro localizacion", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Expediente tecnico: Oficio de autorización de Recursos", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Expediente tecnico Proyecto Ejecutivo Autorizado", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Expediente tecnico: Presupuesto Base", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Procedimiento de Contratacion: Dictamen de adjudicacion directa, licitacion publica nacional o internacional", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Procedimiento de Contratacion: Convocatoria u oificios de invitacion a licitar", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Procedimiento de Contratacion: Base de la licitacion", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Procedimiento de Contratacion: Acta de la junta de aclaraciones", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Procedimiento de Contratacion: Acta de apertura tecnica", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Procedimiento de Contratacion: Acta de apertura economica", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Procedimiento de Contratacion: Cuadro comparativo de las propuestas tecnicas y economicas", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Procedimiento de Contratacion: Analisis detallado de las propuestas tecnicas y economicas", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Procedimiento de Contratacion: Acta de fallo", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Procedimiento de Contratacion: Contrato de la Obra", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Procedimiento de Contratacion: Presupuesto de la obra", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Procedimiento de Contratacion: Programa de ejecucion de la obra", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Procedimiento de Contratacion: Anticipo otorgado", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Procedimiento de Contratacion: Fianza de anticipo", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Procedimiento de Contratacion: Fianza de cumplimiento", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Procedimiento de Contratacion: Convenio adicional o modificatorio", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Procedimiento de Contratacion: Fianzas actualizadas", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Procedimiento de Contratacion: Prorrogas otorgadas", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Procedimiento de Contratacion: Solicitud de conceptos fuera de catalogo y tarjetas de precios unitarios", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Procedimiento de Contratacion: Autorizacion de conceptos fuera de catalogo y tarjetas de precios unitarios", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Procedimiento de Contratacion:  Aviso de inicio de obra", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Procedimiento de Contratacion: Aviso de terminacion de obra", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Procedimiento de Contratacion: Fianza de vicios ocultos ( de contrato y de convenio)", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Procedimiento de Contratacion: Acta de entrega recepcion de la empresa - dependencia", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Ejecucion y Supervision de la Obra: Permisos y Licencias", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Ejecucion y Supervision de la Obra: Bitacora de obra", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Ejecucion y Supervision de la Obra: Numeros generadores", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Ejecucion y Supervision de la Obra: Resultados de la pruebas de laboratorio", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Ejecucion y Supervision de la Obra: Fotografias del avance de la obra", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Control Presupuestario: DEPP´s o polizas de cheques expedidos", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Control Presupuestario: Oficios de modificacion Presupuestaria", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Control Presupuestario: Oficios de cancelacion de recursos", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Ejecucion y Supervision de la Obra: Finiquito", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Ejecucion y Supervision de la Obra: Planos definitivos", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Ejecucion y Supervision de la Obra: Acta de entrega-recepcion dependencia-beneficiarios", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Conclusion de la Obra: Planos Definitivos", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Conclusion de la Obra: Acta de entrega-recepcion dependencia-beneficiarios", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Conclusion de la Obra: Bitacora de obra", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Conclusion de la Obra: Estimaciones", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Observaciones", tipo: "string", obligatorio: false, Descripcion: "Observaciones" },
  ],

  OP03: [
    { campo: "No. del Expediente", tipo: "string", obligatorio: true, Descripcion: "No. de Expediente" },
    { campo: "Tipo de Obra", tipo: "string", obligatorio: true, Descripcion: "Tipo de Obra" },
    { campo: "Programa de Inversión", tipo: "string", obligatorio: true, Descripcion: "Programa de Inversión" },
    { campo: "Nombre de la Obra", tipo: "string", obligatorio: true, Descripcion: "Nombre de la Obra" },
    { campo: "Municipio", tipo: "string", obligatorio: true, Descripcion: "Municipio" },
    { campo: "Localidad", tipo: "string", obligatorio: true, Descripcion: "Localidad" },
    { campo: "Dependencia Beneficiada", tipo: "string", obligatorio: true, Descripcion: "Dependencia Beneficiada" },
    { campo: "Ejercicio Presupuestal", tipo: "number", obligatorio: true, Descripcion: "Ejercicio Presupuestal" },
    { campo: "Ejecutora", tipo: "string", obligatorio: true, Descripcion: "Ejecutora" },
    { campo: "Expediente tecnico: Acuerdo de Ejecucion (Acta de Comité de Obras y Servicios)", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Expediente tecnico: Programa Anual de Obras y Servicios", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Expediente tecnico: Estudios de factibilidad", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Estudios de Impacto Ambiental", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Expediente tecnico: Metas y descripcion del proyecto", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Expediente tecnico: Procedimiento Constructivo", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Expediente tecnico: Planos", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Expediente tecnico: Resumen del Presupuesto", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Expediente tecnico: Programa de Ejecucion", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Expediente tecnico: Croquis de Macro y Micro localizacion", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Expediente tecnico: Oficio de autorización de Recursos", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Expediente tecnico Proyecto Ejecutivo Autorizado", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Expediente tecnico: Presupuesto Base", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Procedimiento de Contratacion: Dictamen de adjudicacion directa, licitacion publica nacional o internacional", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Procedimiento de Contratacion: Convocatoria u oificios de invitacion a licitar", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Procedimiento de Contratacion: Base de la licitacion", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Procedimiento de Contratacion: Acta de la junta de aclaraciones", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Procedimiento de Contratacion: Acta de apertura tecnica", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Procedimiento de Contratacion: Acta de apertura economica", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Procedimiento de Contratacion: Cuadro comparativo de las propuestas tecnicas y economicas", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Procedimiento de Contratacion: Analisis detallado de las propuestas tecnicas y economicas", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Procedimiento de Contratacion: Acta de fallo", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Procedimiento de Contratacion: Contrato de la Obra", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Procedimiento de Contratacion: Presupuesto de la obra", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Procedimiento de Contratacion: Programa de ejecucion de la obra", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Procedimiento de Contratacion: Anticipo otorgado", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Procedimiento de Contratacion: Fianza de anticipo", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Procedimiento de Contratacion: Fianza de cumplimiento", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Procedimiento de Contratacion: Convenio adicional o modificatorio", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Procedimiento de Contratacion: Fianzas actualizadas", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Procedimiento de Contratacion: Prorrogas otorgadas", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Procedimiento de Contratacion: Solicitud de conceptos fuera de catalogo y tarjetas de precios unitarios", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Procedimiento de Contratacion: Autorizacion de conceptos fuera de catalogo y tarjetas de precios unitarios", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Procedimiento de Contratacion:  Aviso de inicio de obra", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Procedimiento de Contratacion: Aviso de terminacion de obra", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Procedimiento de Contratacion: Fianza de vicios ocultos ( de contrato y de convenio)", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Procedimiento de Contratacion: Acta de entrega recepcion de la empresa - dependencia", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Ejecucion y Supervision de la Obra: Permisos y Licencias", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Ejecucion y Supervision de la Obra: Bitacora de obra", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Ejecucion y Supervision de la Obra: Numeros generadores", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Ejecucion y Supervision de la Obra: Resultados de la pruebas de laboratorio", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Ejecucion y Supervision de la Obra: Fotografias del avance de la obra", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Control Presupuestario: DEPP´s o polizas de cheques expedidos", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Control Presupuestario: Oficios de modificacion Presupuestaria", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Control Presupuestario: Oficios de cancelacion de recursos", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Ejecucion y Supervision de la Obra: Finiquito", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Ejecucion y Supervision de la Obra: Planos definitivos", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Ejecucion y Supervision de la Obra: Acta de entrega-recepcion dependencia-beneficiarios", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Conclusion de la Obra: Planos Definitivos", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Conclusion de la Obra: Acta de entrega-recepcion dependencia-beneficiarios", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Conclusion de la Obra: Bitacora de obra", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Conclusion de la Obra: Estimaciones", tipo: "string", obligatorio: true, Descripcion: "Documentación contenida en el expediente unitario de las obras" },
    { campo: "Observaciones", tipo: "string", obligatorio: false, Descripcion: "Observaciones" },
  ],

  OP04: [
    { campo: "Licitacion", tipo: "string", obligatorio: true, Descripcion: "Licitación" },
    { campo: "Obra", tipo: "string", obligatorio: true, Descripcion: "Obra" },
    { campo: "Localidad", tipo: "string", obligatorio: true, Descripcion: "Localidad" },
    { campo: "Municipio", tipo: "string", obligatorio: true, Descripcion: "Municipio" },
    { campo: "Area_Operativa", tipo: "string", obligatorio: true, Descripcion: "Área Operativa" },
    { campo: "Tramite_Actual", tipo: "string", obligatorio: true, Descripcion: "Trámite Actual" },
    { campo: "Observaciones", tipo: "string", obligatorio: false, Descripcion: "Observaciones" },
  ],

  // Estructura para registros de bienes muebles

  ADI02: [
    { campo: "Numero de clasificación", tipo: "string", obligatorio: true, Descripcion: "Número de clasificación del bien mueble" },
    { campo: "Titulo", tipo: "string", obligatorio: true, Descripcion: "Título del bien mueble" },
    { campo: "Acervo Bibliografico: Autor", tipo: "string", obligatorio: true, Descripcion: "Autor del acervo bibliográfico" },
    { campo: "Acervo Bibliografico: Editorial", tipo: "string", obligatorio: true, Descripcion: "Editorial del acervo bibliográfico" },
    { campo: "Acervo Bibliografico: Fecha de Publicacion", tipo: "string", obligatorio: true, Descripcion: "Fecha de publicación del acervo bibliográfico" },
    { campo: "Acervo Bibliografico: No. de Tomos", tipo: "number", obligatorio: true, Descripcion: "Número de tomos del acervo bibliográfico" },
    { campo: "Acervo Hemerografico: Fecha desde ", tipo: "string", obligatorio: false, Descripcion: "Fecha de inicio del acervo hemerográfico" },
    { campo: "Acervo Hemerografico: Fecha hasta ", tipo: "string", obligatorio: false, Descripcion: "Fecha de fin del acervo hemerográfico" },
    { campo: " Acervo Hemerografico: No. de ejemplares", tipo: "number", obligatorio: false, Descripcion: "Número de ejemplares del acervo hemerográfico" },
    { campo: "Estado Fisico", tipo: "string", obligatorio: true, Descripcion: "Estado físico del bien mueble" },
  ],

  ADI01: [
    { campo: "Nombre del sistema, programa o archivo", tipo: "string", obligatorio: true, Descripcion: "Nombre del sistema, programa o archivo" },
    { campo: "Descripcion", tipo: "string", obligatorio: true, Descripcion: "Descripción del Bien" },
    { campo: "Tipo de Respaldo", tipo: "string", obligatorio: true, Descripcion: "Tipo de Respaldo" },
    { campo: "Periodicidad del respaldo", tipo: "string", obligatorio: true, Descripcion: "Periodicidad del respaldo" },
    { campo: "Medio", tipo: "string", obligatorio: true, Descripcion: "Medio" },
    { campo: "Fecha", tipo: "date", obligatorio: true, Descripcion: "Fecha" },
    { campo: "Nombre del Responsable", tipo: "string", obligatorio: true, Descripcion: "Nombre del Responsable" },
    { campo: "Puesto del Responsable", tipo: "string", obligatorio: true, Descripcion: "Puesto del Responsable" },
    { campo: "Observaciones", tipo: "string", obligatorio: false, Descripcion: "Observaciones" },
  ],

  // Estructura para registros de funcionarios

  CF01: [
    { campo: "Unidad Responsable Solicitante", tipo: "string", obligatorio: true, Descripcion: "Nombre" },
    { campo: "Adquisicion: Numero", tipo: "string", obligatorio: true, Descripcion: "Cargo" },
    { campo: "Adquisicion: Fecha", tipo: "date", obligatorio: true, Descripcion: "Área" },
    { campo: "Pedido: NUmero de Contrato", tipo: "string", obligatorio: true, Descripcion: "Teléfono" },
    { campo: "Pedido: Fecha", tipo: "date", obligatorio: true, Descripcion: "Correo Electrónico" },
    { campo: "Tramite Actual", tipo: "string", obligatorio: true, Descripcion: "Correo Electrónico" },
  ],

  CF02: [
    { campo: "Asunto", tipo: "string", obligatorio: true, Descripcion: "Nombre" },
    { campo: "Fecha de Inicio", tipo: "date", obligatorio: true, Descripcion: "Cargo" },
    { campo: "Situacion actual", tipo: "string", obligatorio: true, Descripcion: "Área" },
    { campo: "Observaciones", tipo: "string", obligatorio: false, Descripcion: "Observaciones" },
  ],

  // Estructura para registros de informes

  IG01: [
    { campo: "Clave documental o expediente", tipo: "string", obligatorio: true, Descripcion: "Tipo de Informe" },
    { campo: "Contenido de archivo o expediente", tipo: "string", obligatorio: true, Descripcion: "Fecha" },
    { campo: "Unidad de Concentracion", tipo: "string", obligatorio: true, Descripcion: "Descripción" },
  ],

  IG02: [
    { campo: "Tipo de Acta", tipo: "string", obligatorio: true, Descripcion: "Tipo de Informe" },
    { campo: "Numero de Acta", tipo: "number", obligatorio: true, Descripcion: "Fecha" },
    { campo: "Fecha e Acta", tipo: "date", obligatorio: true, Descripcion: "Descripción" },
    { campo: "Descripcion", tipo: "string", obligatorio: true, Descripcion: "Responsable" },
    { campo: "Observaciones", tipo: "string", obligatorio: false, Descripcion: "Observaciones" },
  ],

  // Estructura para registros de archivos

  TAI01: [
    { campo: "Fecha de Solicitud", tipo: "string", obligatorio: true, Descripcion: "Tipo de Archivo" },
    { campo: "Area que atiende", tipo: "string", obligatorio: true, Descripcion: "Nombre del Archivo" },
    { campo: "No. de expediente o solicitud", tipo: "string", obligatorio: true, Descripcion: "Descripción" },
    { campo: "Estado de Solicitud", tipo: "date", obligatorio: true, Descripcion: "Fecha" },
    { campo: "Fecha limite de Respuesta", tipo: "string", obligatorio: false, Descripcion: "Observaciones" },
    { campo:"Recurso de Revision ", tipo: "string", obligatorio: false, Descripcion: "Recurso de Revision" },
    { campo:"Estatus Actual", tipo: "string", obligatorio: false, Descripcion: "Estatus Actual" },
    { campo:"Observaciones", tipo: "string", obligatorio: false, Descripcion: "Observaciones" },
  ],

  // Estructura para registros de comisiones, honorarios, actas, claves y firmas

  CC01: [
    { campo: "Tipo de Instrumento", tipo: "string", obligatorio: true, Descripcion: "Tipo de Instrumento" },
    { campo: "Objetivo", tipo: "string", obligatorio: true, Descripcion: "Objetivo" },
    { campo: "Partes Involucradas: entre el o la", tipo: "string", obligatorio: true, Descripcion: "Área" },
    { campo: "Partes Involucradas: y el o la", tipo: "string", obligatorio: true, Descripcion: "Área" },
    { campo: " Vigencia: Desde", tipo: "date", obligatorio: true, Descripcion: "Vigencia" },
    { campo: " Vigencia: Hasta", tipo: "date", obligatorio: true, Descripcion: "Vigencia" },
    { campo: "Importe Convenido", tipo: "string", obligatorio: true, Descripcion: "Importe Convenido" },
    { campo: "Observaciones", tipo: "string", obligatorio: false, Descripcion: "Observaciones" },
    
  ],

  CC02: [
    { campo: "Nombre", tipo: "string", obligatorio: true, Descripcion: "Nombre" },
    { campo: "Descripcion", tipo: "string", obligatorio: true, Descripcion: "Cargo" },
    { campo: "Origen", tipo: "string", obligatorio: true, Descripcion: "Área" },
    { campo: "Repercusion Presupuestal", tipo: "string", obligatorio: true, Descripcion: "Firma" },
    { campo: "Vigencia: Desde", tipo: "date", obligatorio: true, Descripcion: "Vigencia" },
    { campo: "Vigencia: Hasta", tipo: "date", obligatorio: true, Descripcion: "Vigencia" },
    { campo: "Acciones Relevantes por concluir", tipo: "string", obligatorio: false, Descripcion: "Observaciones" },
  ],

  CC03: [
    { campo: "Datos del contrato: Nombre del fideicomiso", tipo: "string", obligatorio: true, Descripcion: "Nombre" },
    { campo: "Datos del contrato: Nombre de la fiduciaria", tipo: "string", obligatorio: true, Descripcion: "Cargo" },
    { campo: "Datos del contrato: Nombre de la Instancia Fideicomitente", tipo: "string", obligatorio: true, Descripcion: "Área" },
    { campo: "Datos del contrato: Fideicomisario", tipo: "string", obligatorio: true, Descripcion: "Firma" },
    { campo: "Datos del contrato: Numero de Contrato", tipo: "string", obligatorio: false, Descripcion: "Observaciones" },
    { campo: "Datos del contrato: Fecha de Celebracion", tipo: "date", obligatorio: false, Descripcion: "Observaciones" },
    { campo: "Comentarios", tipo: "string", obligatorio: false, Descripcion: "Comentarios" }
  ],

  // Estructura para registros de actas, claves y firmas

  AG01: [
    { campo: "Tipo de Documento", tipo: "string", obligatorio: true, Descripcion: "Número de Acta" },
    { campo: "Especificar", tipo: "date", obligatorio: true, Descripcion: "Fecha" },
    { campo: "Area Usuaria", tipo: "string", obligatorio: true, Descripcion: "Lugar" },
    { campo: "Ultima Forma Utilizada: Folio", tipo: "string", obligatorio: true, Descripcion: "Descripción" },
    { campo: "Ultima Forma Utilizada: Fecha", tipo: "string", obligatorio: true, Descripcion: "Responsable" },
    { campo: "Ultima Forma Utilizada: Conceptos", tipo: "string", obligatorio: false, Descripcion: "Observaciones" },
    { campo : "Folios sin utilizar: desde ", tipo: "string", obligatorio: false, Descripcion: "Observaciones" },
    { campo : "Folios sin utilizar: hasta ", tipo: "string", obligatorio: false, Descripcion: "Observaciones" },
    {campo: "Folios sin utilizar: Cantidad ", tipo: "number", obligatorio: false, Descripcion: "Observaciones" },
    {campo:"Responsable de su custodia: Nombre y puesto", tipo: "string", obligatorio: false, Descripcion: "Responsable de su custodia" },
    { campo: "Comentarios", tipo: "string", obligatorio: false, Descripcion: "Comentarios" }

  ],

  AG02: [
    { campo: "Especificar", tipo: "string", obligatorio: true, Descripcion: "Número de Acta" },
    { campo: "Area Usuaria", tipo: "date", obligatorio: true, Descripcion: "Fecha" },
    { campo: "Cantidad", tipo: "string", obligatorio: true, Descripcion: "Descripción" },
    { campo: "Responsable de su custodia: Nombre y cargo", tipo: "string", obligatorio: true, Descripcion: "Responsable" },
    { campo: "En uso o Inutilizado", tipo: "string", obligatorio: false, Descripcion: "Observaciones" },
  ],

  AG03: [
    { campo: "Institución que Autorizó la Firma o Clave Electrónica", tipo: "string", obligatorio: true, Descripcion: "Institución que autorizó la firma o clave electrónica" },
    { campo: "Número de Cuenta", tipo: "string", obligatorio: true, Descripcion: "Número de Cuenta" },
    { campo: "Usuario", tipo: "string", obligatorio: true, Descripcion: "Usuario" },
    { campo: "Nombre del Sistema o Proceso", tipo: "string", obligatorio: true, Descripcion: "Nombre del Sistema o Proceso" },
    { campo: "tipo de Clave", tipo: "string", obligatorio: true, Descripcion: "Tipo de Clave" },
    { campo: "Datos del personal con acceso: Nombre", tipo: "string", obligatorio: true, Descripcion: "Nombre del personal con acceso" },
    { campo: "Datos del personal con acceso: Puesto", tipo: "string", obligatorio: true, Descripcion: "Cargo del personal con acceso" },
  ],

  AG04: [
    { campo: "Institución que Autorizó la Firma o Clave Electrónica", tipo: "string", obligatorio: true, Descripcion: "Institución que autorizó la firma o clave electrónica" },
    { campo: "Número de Cuenta", tipo: "string", obligatorio: true, Descripcion: "Número de Cuenta" },
    { campo: "Usuario de la Firma o Clave Electrónica: nombre", tipo: "string", obligatorio: true, Descripcion: "Usuario" },
    { campo: "Usuario de la Firma o Clave Electrónica: Cargo", tipo: "string", obligatorio: true, Descripcion: "Cargo del Usuario" },
    { campo: "Vigencia de la Clave o Firma: Desde", tipo: "date", obligatorio: true, Descripcion: "Vigencia de la Clave o Firma" },
    { campo: "Documento que acredita la Cancelacion de la Clave o Firma: Número ", tipo: "string", obligatorio: true, Descripcion: "Número del Documento" },
    { campo: "Documento que acredita la Cancelacion de la Clave o Firma: Fecha ", tipo: "date", obligatorio: true, Descripcion: "Fecha de Cancelación" },
    { campo: "Observaciones", tipo: "string", obligatorio: false, Descripcion: "Observaciones" },
  ],

  AR01: [
    { campo: "Síntesis del Asunto", tipo: "string", obligatorio: true, Descripcion: "Área" },
    { campo: "Área Responsable", tipo: "string", obligatorio: true, Descripcion: "Responsable que entrega" },
    { campo: "Fecha de Atención", tipo: "string", obligatorio: true, Descripcion: "Responsable que recibe" },
    { campo: "Observaciones", tipo: "string", obligatorio: false, Descripcion: "Observaciones" },
  ],

  // Estructura para registros de bienes muebles e inmuebles

  RM01: [
    { campo: "Descripcion", tipo: "string", obligatorio: true, Descripcion: "Descripción" },
    { campo: "Marca", tipo: "string", obligatorio: true, Descripcion: "Marca" },
    { campo: "Modelo", tipo: "string", obligatorio: true, Descripcion: "Modelo" },
    { campo: "No. de serie", tipo: "string", obligatorio: true, Descripcion: "No. de serie" },
    { campo: "No. de patrimonio", tipo: "string", obligatorio: true, Descripcion: "No. de patrimonio" },
    { campo: "No. de resguardo interno", tipo: "string", obligatorio: true, Descripcion: "No. de resguardo interno" },
    { campo: "Estado de uso", tipo: "string", obligatorio: true, Descripcion: "Estado de uso" },
    { campo: "UR", tipo: "string", obligatorio: true, Descripcion: "UR" },
    { campo: "Número de Empleado", tipo: "number", obligatorio: true, Descripcion: "Número de Empleado" },
    { campo: "Responsable", tipo: "string", obligatorio: true, Descripcion: "Responsable" },
    { campo: "Puesto del usuario resguardante", tipo: "string", obligatorio: true, Descripcion: "Puesto del usuario resguardante" },
  ],


  RM02: [
    { campo: "Marca", tipo: "string", obligatorio: true, Descripcion: "Marca" },
    { campo: "Modelo", tipo: "string", obligatorio: true, Descripcion: "Modelo" },
    { campo: "Color", tipo: "string", obligatorio: true, Descripcion: "Color" },
    { campo: "Placas / Matrícula / Registro", tipo: "string", obligatorio: true, Descripcion: "Placas / Matrícula / Registro" },
    { campo: "No. de serie", tipo: "string", obligatorio: true, Descripcion: "No. de serie" },
    { campo: "No. de motor", tipo: "string", obligatorio: true, Descripcion: "No. de motor" },
    { campo: "Estado físico", tipo: "string", obligatorio: true, Descripcion: "Estado físico" },
    { campo: "UR", tipo: "string", obligatorio: true, Descripcion: "UR" },
    { campo: "Clave Patrimonial", tipo: "string", obligatorio: true, Descripcion: "Clave Patrimonial" },
    { campo: "Número de resguardo interno", tipo: "string", obligatorio: true, Descripcion: "Número de resguardo interno" },
    { campo: "Número de Empleado del resguardante", tipo: "number", obligatorio: true, Descripcion: "Número de Empleado del resguardante" },
    { campo: "Responsable del uso del vehículo", tipo: "string", obligatorio: true, Descripcion: "Responsable del uso del vehículo" },
    { campo: "Cargo de usuario resguardante", tipo: "string", obligatorio: true, Descripcion: "Cargo de usuario resguardante" },
  ],

  RM03: [
    { campo: "Descripcion", tipo: "string", obligatorio: true, Descripcion: "Descripción" },
    { campo: "Marca", tipo: "string", obligatorio: true, Descripcion: "Marca" },
    { campo: "Modelo", tipo: "string", obligatorio: true, Descripcion: "Modelo" },
    { campo: "Serie", tipo: "string", obligatorio: true, Descripcion: "Serie" },
    { campo: "Clave patrimonial", tipo: "string", obligatorio: true, Descripcion: "Clave patrimonial" },
    { campo: "No. de resguardo interno", tipo: "string", obligatorio: true, Descripcion: "No. de resguardo interno" },
    { campo: "Número de Empleado", tipo: "number", obligatorio: true, Descripcion: "Número de Empleado" },
    { campo: "Responsable", tipo: "string", obligatorio: true, Descripcion: "Responsable" },
    { campo: "Estado físico", tipo: "string", obligatorio: true, Descripcion: "Estado físico" },
    { campo: "UR", tipo: "string", obligatorio: true, Descripcion: "UR" },
    { campo: "Ubicacion_actual", tipo: "string", obligatorio: true, Descripcion: "Ubicación actual" },
    { campo: "Observaciones", tipo: "string", obligatorio: false, Descripcion: "Observaciones" },
  ],

  RM04: [
    { campo: "Clave patrimonial", tipo: "string", obligatorio: true, Descripcion: "Clave patrimonial" },
    { campo: "Descripcion", tipo: "string", obligatorio: true, Descripcion: "Descripción" },
    { campo: "Marca", tipo: "string", obligatorio: true, Descripcion: "Marca" },
    { campo: "Modelo", tipo: "string", obligatorio: true, Descripcion: "Modelo" },
    { campo: "No. Serie", tipo: "string", obligatorio: true, Descripcion: "No. Serie" },
    { campo: "Cantidad", tipo: "number", obligatorio: true, Descripcion: "Cantidad" },
    { campo: "Precio Unitario", tipo: "number", obligatorio: true, Descripcion: "Precio Unitario" },
    { campo: "Precio Total", tipo: "number", obligatorio: true, Descripcion: "Precio Total" },
    { campo: "Localización", tipo: "string", obligatorio: true, Descripcion: "Localización" },
    { campo: "UR", tipo: "string", obligatorio: true, Descripcion: "UR" }, // minúsculas como pediste
  ],

  RM05: [
    { campo: "Tipo de bien", tipo: "string", obligatorio: true, Descripcion: "Tipo de bien" },
    { campo: "Descripcion del bien", tipo: "string", obligatorio: true, Descripcion: "Descripción del bien" },
    { campo: "Marca", tipo: "string", obligatorio: true, Descripcion: "Marca" },
    { campo: "Modelo", tipo: "string", obligatorio: true, Descripcion: "Modelo" },
    { campo: "No. de serie", tipo: "string", obligatorio: true, Descripcion: "No. de serie" },
    { campo: "Estado físico", tipo: "string", obligatorio: true, Descripcion: "Estado físico" },
    { campo: "Ubicación", tipo: "string", obligatorio: true, Descripcion: "Ubicación" },
    { campo: "Nombre del otorgante", tipo: "string", obligatorio: true, Descripcion: "Nombre del otorgante" },
    { campo: "Fecha de firma del comodato", tipo: "date", obligatorio: true, Descripcion: "Fecha de firma del comodato" },
    { campo: "Periodo", tipo: "string", obligatorio: true, Descripcion: "Período" },
  ],

  RM06: [
    { campo: "Descripción", tipo: "string", obligatorio: true, Descripcion: "Descripción" },
    { campo: "Tipo de predio", tipo: "string", obligatorio: true, Descripcion: "Tipo de predio" },
    { campo: "Superficie m2", tipo: "number", obligatorio: true, Descripcion: "Superficie m2" },
    { campo: "Calle y número", tipo: "string", obligatorio: true, Descripcion: "Calle y número" },
    { campo: "Localidad", tipo: "string", obligatorio: true, Descripcion: "Localidad" },
    { campo: "Estatus legal", tipo: "string", obligatorio: true, Descripcion: "Estatus legal" },
    { campo: "Descripción de la situación jurídica y/o administrativa", tipo: "string", obligatorio: true, Descripcion: "Descripción de la situación jurídica y/o administrativa" },
  ],

  RM07: [
    { campo: "No de Inventario", tipo: "string", obligatorio: true, Descripcion: "No. DE INVENTARIO" },
    { campo: "No de CTA Predial", tipo: "string", obligatorio: true, Descripcion: "No. CTA. PREDIAL" },
    { campo: "Ubicación", tipo: "string", obligatorio: true, Descripcion: "UBICACIÓN" },
    { campo: "Superficie Terreno MTS2", tipo: "number", obligatorio: true, Descripcion: "SUPERFICIE TERRENO MTS2" },
    { campo: "Zona", tipo: "string", obligatorio: true, Descripcion: "ZONA" },
    { campo: "Doct. que acredita la posesion", tipo: "string", obligatorio: true, Descripcion: "DOCT. QUE ACREDITA LA POSESION" },
    { campo: "Fecha de adquisicion", tipo: "date", obligatorio: true, Descripcion: "FECHA DE ADQUISICIÓN" },
    { campo: "Costo de adquisicion", tipo: "number", obligatorio: true, Descripcion: "COSTO DE ADQUISICIÓN" },
    { campo: "Uso o destino", tipo: "string", obligatorio: true, Descripcion: "USO O DESTINO" },
    { campo: "Comentarios", tipo: "string", obligatorio: false, Descripcion: "COMENTARIOS" }, // minúsculas como pediste
  ],

  RM08: [
    { campo: "Numero de registro y o_inventario", tipo: "string", obligatorio: true, Descripcion: "Número de registro y/o inventario" },
    { campo: "Titulo de la obra articulo", tipo: "string", obligatorio: true, Descripcion: "Título de la obra / artículo" },
    { campo: "Descripción", tipo: "string", obligatorio: true, Descripcion: "Descripción" },
    { campo: "Ubicación", tipo: "string", obligatorio: true, Descripcion: "Ubicación" },
    { campo: "Certificado de autenticidad", tipo: "string", obligatorio: true, Descripcion: "Certificado de autenticidad" },
    { campo: "Estado físico", tipo: "string", obligatorio: true, Descripcion: "Estado físico" },
    { campo: "Datos del resguardante Nombre", tipo: "string", obligatorio: true, Descripcion: "Datos del resguardante Nombre" },
    { campo: "Datos del resguardante Puesto", tipo: "string", obligatorio: true, Descripcion: "Datos del resguardante Puesto" },
    { campo: "Datos del resguardante Num de resguardo", tipo: "string", obligatorio: true, Descripcion: "Datos del resguardante Núm. de resguardo" },
    { campo: "Observaciones", tipo: "string", obligatorio: false, Descripcion: "Observaciones" },
  ],

  RM09: [
    { campo: "Especie", tipo: "string", obligatorio: true, Descripcion: "Especie" },
    { campo: "Cantidad de planta en existencia", tipo: "number", obligatorio: true, Descripcion: "Cantidad de planta en existencia" },
    { campo: "Tipo de produccion", tipo: "string", obligatorio: true, Descripcion: "Tipo de producción" },
    { campo: "Fecha de siembra", tipo: "date", obligatorio: true, Descripcion: "Fecha de siembra" },
    { campo: "Talla", tipo: "string", obligatorio: true, Descripcion: "Talla" },
    { campo: "Observaciones", tipo: "string", obligatorio: false, Descripcion: "Observaciones" },
  ],

  RM10: [
    { campo: "Nombre común", tipo: "string", obligatorio: true, Descripcion: "Nombre común" },
    { campo: "Nombre científico", tipo: "string", obligatorio: true, Descripcion: "Nombre científico" },
    { campo: "Clave", tipo: "string", obligatorio: true, Descripcion: "Clave" },
    { campo: "Origen", tipo: "string", obligatorio: true, Descripcion: "Origen" },
    { campo: "Familia", tipo: "string", obligatorio: true, Descripcion: "Familia" },
    { campo: "Sexo", tipo: "string", obligatorio: true, Descripcion: "Sexo" },
    { campo: "Marcaje", tipo: "string", obligatorio: true, Descripcion: "Marcaje" },
    { campo: "Fecha Alta", tipo: "date", obligatorio: true, Descripcion: "Fecha Alta" },
    { campo: "Observaciones", tipo: "string", obligatorio: false, Descripcion: "Observaciones" },
  ],

  RM11: [
    { campo: "Nombre común del animal", tipo: "string", obligatorio: true, Descripcion: "Nombre común del animal" },
    { campo: "Ubicación física", tipo: "string", obligatorio: true, Descripcion: "Ubicación física" },
    { campo: "No. de resguardo", tipo: "string", obligatorio: true, Descripcion: "No. de resguardo" },
    { campo: "Observaciones", tipo: "string", obligatorio: false, Descripcion: "Observaciones" },
  ],

  RM12: [
    { campo: "Descripción", tipo: "string", obligatorio: true, Descripcion: "Descripción" },
    { campo: "Tipo y calibre", tipo: "string", obligatorio: true, Descripcion: "Tipo y calibre" },
    { campo: "Marca y modelo", tipo: "string", obligatorio: true, Descripcion: "Marca y modelo" },
    { campo: "Matrícula", tipo: "string", obligatorio: true, Descripcion: "Matrícula" },
    { campo: "No. de serie", tipo: "string", obligatorio: true, Descripcion: "No. de serie" },
    { campo: "No. de registro", tipo: "string", obligatorio: true, Descripcion: "No. de registro" },
    { campo: "UR", tipo: "string", obligatorio: true, Descripcion: "UR" },
    { campo: "Estado", tipo: "string", obligatorio: true, Descripcion: "Estado" },
    { campo: "No. de inventario", tipo: "string", obligatorio: true, Descripcion: "No. de inventario" },
    { campo: "No. de resguardo", tipo: "string", obligatorio: true, Descripcion: "No. de resguardo" },
    { campo: "Número de empleado del responsable", tipo: "number", obligatorio: true, Descripcion: "Número de empleado del responsable" },
    { campo: "Nombre del responsable", tipo: "string", obligatorio: true, Descripcion: "Nombre del responsable" },
    { campo: "Puesto del responsable", tipo: "string", obligatorio: true, Descripcion: "Puesto del responsable" },
    { campo: "Observaciones", tipo: "string", obligatorio: false, Descripcion: "Observaciones" },
  ],

  RM13: [
    { campo: "Nombre del paquete", tipo: "string", obligatorio: true, Descripcion: "Nombre del paquete" },
    { campo: "Licencia", tipo: "string", obligatorio: true, Descripcion: "Licencia" },
    { campo: "Versión", tipo: "string", obligatorio: true, Descripcion: "Versión" },
    { campo: "No. de serie", tipo: "string", obligatorio: true, Descripcion: "No. de serie" },
    { campo: "Origen", tipo: "string", obligatorio: true, Descripcion: "Origen" },
    { campo: "Fecha de adquisición", tipo: "date", obligatorio: true, Descripcion: "Fecha de adquisición" },
    { campo: "Equipo en que opera", tipo: "string", obligatorio: true, Descripcion: "Equipo en que opera" },
    { campo: "Usuario", tipo: "string", obligatorio: true, Descripcion: "Usuario" },
    { campo: "Medio de almacenamiento", tipo: "string", obligatorio: true, Descripcion: "Medio de almacenamiento" },
    { campo: "No. de manuales", tipo: "number", obligatorio: true, Descripcion: "No. de manuales" },
  ],

  RM14: [
    { campo: "Nombre del sistema / subsistema", tipo: "string", obligatorio: true, Descripcion: "Nombre del sistema / subsistema" },
    { campo: "Fase de", tipo: "string", obligatorio: true, Descripcion: "Fase de" },
    { campo: "Fecha de liberación", tipo: "date", obligatorio: true, Descripcion: "Fecha de liberación" },
    { campo: "Origen", tipo: "string", obligatorio: true, Descripcion: "Origen" },
    { campo: "Equipo en que opera", tipo: "string", obligatorio: true, Descripcion: "Equipo en que opera" },
    { campo: "Medio de distribución", tipo: "string", obligatorio: true, Descripcion: "Medio de distribución" },
    { campo: "Documentación", tipo: "string", obligatorio: true, Descripcion: "Documentación" },
    { campo: "UR", tipo: "string", obligatorio: true, Descripcion: "UR" },
    { campo: "Código fuente", tipo: "string", obligatorio: true, Descripcion: "Código fuente" },
  ],

  RM15: [

    { campo: "Descripción del equipo", tipo: "string", obligatorio: true, Descripcion: "Descripción del equipo" },
    { campo: "Especificaciones", tipo: "string", obligatorio: true, Descripcion: "Especificaciones" },
    { campo: "Marca", tipo: "string", obligatorio: true, Descripcion: "Marca" },
    { campo: "Modelo", tipo: "string", obligatorio: true, Descripcion: "Modelo" },
    { campo: "No. de serie", tipo: "string", obligatorio: true, Descripcion: "No. de serie" },
    { campo: "Estado", tipo: "string", obligatorio: true, Descripcion: "Estado" },
    { campo: "Área de asignación", tipo: "string", obligatorio: true, Descripcion: "Área de asignación" },
    { campo: "Ubicación física del equipo", tipo: "string", obligatorio: true, Descripcion: "Ubicación física del equipo" },
    { campo: "Número de Empleado del responsable", tipo: "number", obligatorio: true, Descripcion: "Número de Empleado del responsable" },
    { campo: "Nombre del usuario responsable", tipo: "string", obligatorio: true, Descripcion: "Nombre del usuario responsable" },
    { campo: "Puesto del usuario responsable", tipo: "string", obligatorio: true, Descripcion: "Puesto del usuario responsable" },
    { campo: "No. de resguardo", tipo: "string", obligatorio: true, Descripcion: "No. de resguardo" },
  ],

  RM16: [
    { campo: "Área", tipo: "string", obligatorio: true, Descripcion: "Área" },
    { campo: "Descripción", tipo: "string", obligatorio: true, Descripcion: "Descripción" },
    { campo: "Responsable", tipo: "string", obligatorio: true, Descripcion: "Responsable" },
    { campo: "Número de Empleado", tipo: "number", obligatorio: true, Descripcion: "Número de Empleado" },
    { campo: "Fecha de Entrega", tipo: "date", obligatorio: true, Descripcion: "Fecha de Entrega" },
    { campo: "URE", tipo: "string", obligatorio: true, Descripcion: "URE" },
    { campo: "Observaciones", tipo: "string", obligatorio: false, Descripcion: "Observaciones" },
  ],



}