// lib/estructuras.ts por ahora en el mismo archivo
export const EstructuraDatosPorClave: Record<string, string[]> = {
  // Marco Jurídico
  MJ01: ["ORDENAMIENTO", "TITULO", "FECHA DE EMISION"], // CHECKED
  AR01: ["ASUNTO", "DESCRIPCION", "FECHA INICIO", "RESPONSABLE", "ESTATUS"],

  // Recursos Presupuestales
  RF01: ["PARTIDA", "DENOMINACION","PRESUPUESTO", "AUTORIZADO","AMPLIACIONES Y/O REDUCCIONES", "MODIFICADO", "EJERCIDO", "POR EJERCER"],
  RF02: ["ORIGEN DEL RECURSO", "PARTIDA", "DESCRIPCION", "PRESUPUESTO", "AUTORIZADO", "AMPLIACIONES Y/O REDUCCIONES", "MODIFICADO", "EJERCIDO", "POR EJERCER"],
  RF03: ["RAMO", "PROGRAMA", "DEPENDENCIA EJECUTORA", "NÚMERO DEL CONVENIO O REFERENCIA DE LA AUTORIZACIÓN", "IMPORTE", "APROBADO", "MODIFICADO", "EJERCIDO", "POR EJERCER", "NUMERO DE ACCIONES", "APROBADAS","EJECUTADAS", "PENDENTES","OBSERVACIONES"],
  RF04: ["NOMBRE DEL PROGRAMA", "NUMERO DEL CAPITULO", "NOMBRE DEL CAPITULO", "PRESUPUESTO", "AUTORIZADO", "AMPLIACIONES Y/O REDUCCIONES", "MODIFICADO", "EJERCIDO", "POR EJERCER"],
  RF05: ["INSTITUCION BANCARIA", "CLAVE DE SUCURSAL", "TIPO DE CUENTA", "NUMERO DE CUENTA", "FIRMAS REGISTRADAS", "NOMBRE", "CARGO", "FOLIO DEL ULTIMO CHEQUE EXPEDIDO","SALDO SEGUN BANCO","CARGOS NO CORRESPONDIDOS", "ABONOS NO CORRESPONDIDOS", "SALDO SEGUN REGISTROS", "RESPONSABLE DEL MANEJO"],
  RF06: ["OFICIO DE AUTORIZACION NUM.", "DE FECHA", "NOMBRE DEL RESPONSABLE", "CARGO DEL RESPONSABLE", "IMPORTE AL VERIFICAR","DESTINO DEL FONDO ASIGNADO", "RESULTADO DEL ULTIMO ARQUEO PRACTICADO","SALDO EN CUENTA DE CHEQUES", "NO. DE CUENTA", "BANCO", "BANCO", "FECHA", "SALDO", "MONTO DISPONIBLE EN EFECTIVO", "COMPROBANTES", "ACREEDORES DIVERSOS", "DEUDORES DIVERSOS", "DOCUMENTOS POR RECUPERAR"],
  RF07: ["NUMERO DE FOLIO DEL CONTRARECIBO", "NOMBRE DEL BENEFICIARIO", "FECHA DE RECEPCION", "NUMERO DE ESTIMACION O FACTURA", "IMPORTE TOTAL", "OBSERVACIONES"],
  RF08: ["FECHA", "NUMERO DE CHEQUE", "CUENTA", "BANCO", "MONTO", "BENEFICIARIO", "CONCEPTO"],
  RF09: ["ÁREA GENERADORA DEL INGRESO", "CONCEPTO QUE DA ORIGEN AL INGRESO", "FECHA DEL INGRESO", "DOCUMENTO QUE IDENTIFICA AL INGRESO", "IMPORTE DEL INGRESO: MONTO", "IMPORTE DEL INGRESO: CUENTA BANCARIA DONDE SE DEPOSITARA", ""],
  RF11: ["NOMBRE DEL DEUDOR", "CONCEPTO", "DOCUMENTO QUE ACREDITA LA CUENTA POR COBRAR: FECHA", "DOCUMENTO QUE ACREDITA LA CUENTA POR COBRAR: TIPO", "DOCUMENTO QUE ACREDITA LA CUENTA POR COBRAR: FOLIO", "DOCUMENTO QUE ACREDITA LA CUENTA POR COBRAR: IMPORTE", "DOCUMENTO QUE ACREDITA LA CUENTA POR COBRAR: FECHA DE VENCIMIENTO", "DOCUMENTO QUE ACREDITA LA CUENTA POR COBRAR: NUMERO CONTABLE", "DOCUMENTO QUE ACREDITA LA CUENTA POR COBRAR: TITULO", "DOCUMENTO QUE ACREDITA LA CUENTA POR COBRAR: SALDO VENCIDO", "OBSERVACIONES"],
  RF12: ["CONCEPTO", "DOCUMENTO QUE ACREDITA LA CUENTA POR PAGAR: FECHA", "DOCUMENTO QUE ACREDITA LA CUENTA POR PAGAR: TIPO", "DOCUMENTO QUE ACREDITA LA CUENTA POR PAGAR: FOLIO", "DOCUMENTO QUE ACREDITA LA CUENTA POR PAGAR: DEPENDENCIA", "DOCUMENTO QUE ACREDITA LA CUENTA POR PAGAR: PARTIDA", "DOCUMENTO QUE ACREDITA LA CUENTA POR PAGAR: FECHA DE VENCIMIENTO", "DATOS DE LA CUENTA POR PAGAR: NÚMERO", "DATOS DE LA CUENTA POR PAGAR: TÍTULO", "DATOS DE LA CUENTA POR PAGAR: SALDO VENCIDO", "OBSERVACIONES"],
  RF13: ["CONCEPTO DEL IMPUESTO", "ENTEROS PROVISIONALES: PERIODO; POR PAGAR", "ENTEROS PROVISIONALES: PERIODO; T/D", "ENTEROS PROVISIONALES: IMPORTE; CLAVE", "ENTEROS PROVISIONALES: MULTAS Y RECARGOS", "DECLARACIONES ANUALES: PRESENTADAS", "DECLARACIONES ANUALES: POR PRESENTAR", "DECLARACIONES ANUALES: AÑO"],
  RF14: ["TIPO DE POLIZA", "COMPAÑIA", "MONTO", "COBERTURA", "VIGENCIA","DEL","HASTA", "OBSERVACIONES"],
  RF15: ["COMPAÑIA ASEGURADORA", "TIPO DE FIANZA O GARANTIA", "CONCEPTO U OBRA DE LA FIANZA O GARANTÍA", "COBERTURA DE LA FIANZA O GARANTÍA", "MONTO DE LA FIANZA O GARANTÍA", "VIGENCIA DE LA FIANZA O GARANTÍA","VIGENCIA","DEL","AL","OBSERVACIONES"],
  RF16: ["DESCRIPCION DEL CONVENIO O CONTRATO", "NOMBRE QUIEN CONVIENE O CONTRATA POR LA UNIDA RESPONSABLE", "IMPORTE", "PERIODO"],
  RF17: ["TIPO DE DOCUMENTO", "FOLIO", "DEL", "AL", "FECHA DE ULTIMO REGISTRO", "OBSERVACIONES"],


  // Contratos y Convenios
  CCL01: ["TIPO DE INSTRUMENTO", "OBJETIVO", "PARTES INVOLUCRADAS", "VIGENCIA", "IMPORTE CONVENIDO", "OBSERVACIONES"],
  CCL02: ["NOMBRE", "DESCRIPCION", "ORIGEN", "RECUPERACION PRESUPUESTAL", "VIGENCIA", "ACCIONES RELEVANTES POR CONCLUIR"],
  CCL03: ["DATOS DEL CONTRATO"  , "monto", "objetivo", "fecha_inicio", "fecha_fin"],

  // Estructura Interna
  ENI01: ["url", "blob"], // organigrama pdf libre
  ENI02: ["TIPO", 
    "NOMBRE",
    "FECHA DE PUBLICACION",
    "VERSION",
    "OBSERVACIONES"
  ], // reglamento interno y manuales generales
  ENI03: ["NÚMERO DE SESIÓN",
    "FECHA DE LA SESIÓN",
    "ORDINARIA O EXTRAORDINARIA",
    "DATOS DEL ACUERDO: TIPO DE ACUERDO",
    "DATOS DEL ACUERRDO: DESCRIPCION BREVE",
    "DATOS DEL ACUERDO: ESPONSABLE",
    "DATOS DEL ACUERDO: AREAS INVOLUCRADAS",
    "ESTATUS DEL ACUERDO: PORCENTAJE DEL AVANCE",
    "ESTATUS DEL ACUERDO: OBSERVACIONES"
  ], // Acuerdo de organos de gobierno y Actas de consejo
  ENI04: ["CARGO",
    "CON DERECHO A ",
    "FECHA DE INICIO DEL CARGO",
    "PERIODICIDAD DE LA REUNION",
    "OBSERVACIONES"
  ], // representaciones y cargos honoríficos
  ENI05: ["NOMBRE Y PUESTO DEL SERVIDOR QUE OTORGA EL PODER",
    "TIPO DE PODER OTORGADO",
    "FECHA DE OTORGAMIENTO",
    "NOTARIO NO.",
    "INSCRITO AL REGISTRO PÚBLICO DE LA PROPIEDAD Y EL COMERCIO",
    "OBSERVACIONES"], // poderes otorgados

  // Recursos Humanos
  RRH01: ["NUMERO DE EMPLEADO",
    "NOMBRE",
    "RFC",
    "PLAZA (CATEGORIA)",
    "TIPO DE ENCARGO",
    "FECHA DE INGRESO",
    "SUELDO",
    "OTRAS PERCEPCIONES",
    "TOTAL",
    "UNIDAD DE ADSCRIPCION",
    "AREA LABORAL",
    "OBSERVACIONES",
    "ESTATUS: Base, Apoyo, Comisionado",
  ], // plantilla de personal
  RRH02: ["NOMBRE",
    "RFC",
    "FECHA DE INICIO DE CONTRATO",
    "FECHA DE FIN DE CONTRATO",
    "FUENTE DE RECURSO",
    "ACTIVIDADES A DESARROLLAR",
    "SALARIO",
    "OTRAS PERCEPCIONES",
    "TOTAL",
    "UNIDAD DE ADSCRIPCION",
    "AREA LABORAL"
  ], // personal de honorarios

  // Inventario de Bienes
  IBM01: [
    "ARTICULO",
    "MARCA",
    "MODELO",
    "NUMERO DE SERIE",
    "NUMERO DE PATRIMONIO",
    "CANTIDAD",
    "VALOR",
    "UBICACION",
    "RESPONSABLE",

  ], // MObiliario de oficina, vehiculos, maquinaria y equipo
  IBM02: ["CLAVE PATRIMONIAL",
    "DESCRIPCION",
    "MARCA",
    "MODELO",
    "NO. DE SERIE",
    "CANTIDAD",
    "VALOR",
    "UBICACION",
    "RESPONSABLE"], // Almacenes de papeleria y plantas de vivero
  IBM03: ["TIPO DE BIEN",
    "DESCRIPCION",
    "MARCA",
    "MODELO",
    "NO. DE SERIE",
    "ESTADO FÍSICO",
    "UBICACION",
    "RESPONSABLE",
    "NOMBRE DE OTORGANTE",
    "FECHA DE FIRMA DE COMODATO"
  ], // Inventario de bienes en comodato
  IBM04: [
    "DESCRIPCION",
    "TIPO DE PREDIO",
    "CALLE Y NÚMERO",
    "LOCALIDAD",
    "OBSERVACIONES",
  ], // Bienes inmuebes de la dependencia
  IBM05: [
    "NUMERO DE REGISTRO O INVENTARIO",
    "TITULO DE LA OBRA",
    "DESCRIPCION",
    "UBICACION",
    "CERTIFICADO DE AUTENTICIDAD",
    "ESTADO FISICO",
    "OBSERVACIONES"
  ], // Inventario de arte
  IBM06: [
    "NOMBRE COMUN",
    "NOMBRE CIENTIFICO",
    "CLAVE",
    "ORIGEN",
    "SEXO",
    "MARCADO",
    "FECHA DE ALTA",
    "OBSERVACIONES"
  ], //Inventario Faunistico (especimen y taxidemnizados)
  // Inventario de Armamento, accesorios de seguridad y municiones
  IBM07: [
    "TIPO DE ARMAMENTO",
    "DESCRIPCION",
    "MARCA",
    "MODELO",
    "NUMERO DE SERIE",
    "CANTIDAD",
    "UBICACION",
    "RESPONSABLE",
    "OBSERVACIONES"
  ],
  // Inventario de Software (sistemas desarrolados y paquetes computacionales)
  IBM08: [
    "NOMBRE DEL SOFTWARE",
    "VERSION",
    "PROVEEDOR",
    "NUMERO DE SERIE",
    "MANUAL",
    "LICENCIA",
    "EQUIPO EN EL QUE OPERA",
    "DOCUMENTACION"
  ],
  // Inventario de tecnologia (equipos de computo y telecomunicaciones)
  IBM09: [
    "NOMBRE DEL EQUIPO",
    "MARCA",
    "MODELO",
    "NUMERO DE SERIE",
    "CANTIDAD",
    "UBICACION",
    "RESPONSABLE",
    "OBSERVACIONES"
  ],

  // Documentación y Archivo
  DA01: ["SISTEMA", "FRECUENCIA", "ULTIMO_RESPALDO", "RESPONSABLE"],
  DA02: ["TITULO", "AUTOR", "TIPO", "UBICACION"],
  DA03: ["TIPO", "DESCRIPCION", "FECHA_INICIO", "FECHA_FIN", "RESPONSABLE"],
  DA04: ["TIPO", "DESCRIPCION", "FECHA_INICIO", "FECHA_FIN", "RESPONSABLE"],
  DA05: ["TIPO", "DESCRIPCION", "FECHA_INICIO", "FECHA_FIN", "RESPONSABLE"],
  DA07: ["EXPEDIENTE", "PROYECTO", "UBICACION", "RESPONSABLE"],

  // Asuntos Legales
  ALA01: ["ASUNTO", "TIPO", "ESTADO", "ABOGADO", "FECHA DE INICIO"],
  ALA02: ["TIPO DE AUDITORIA",
    "PERIODO DE LA AUDITORIA",
    "DATOS DE LA AUDITORIA: REALIZADA POR",
    "DATOS DE LA AUDITORIA: OBSERVACIONES", // Observaciones de Auditorias pendientes
    "DATOS DE LA AUDITORIA: OBSERVACIONES ATENDIDAS",
    "DATOS DE LA AUDITORIA: OBSERVACIONES PENDIENTES",
    "ESTATUS DE LA AUDITORIA: SITUACIÓN ACTUAL"
  ],

  // Programas y Proyectos FORMATO LIBRE PDF 
  PP01: ["url", "blob"],// PDF libre
  PP02: ["TIPO DE DOCUMENTO", "NOMBRE", "FECHA", "OBSERVACIONES"],// checked

  // Transparencia
  TA01: ["SOLICITUD", "SOLICITANTE", "FECHA", "ESTATUS", "RESPUESTA"],

  // Por defecto
  default: ["*"]
};

export const CALVES_CON_PDF: Record<string, string[]> = {
  PP01: ["url", "blob"],
  ENI01: ["url", "blob"]
}